"""Shared Day-1 contract vocabulary."""

AEG_VERSION = "0.1.0"
SAFE_DEFAULT = "hold_current_state"

LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
RISK_LEVELS = (LOW, MEDIUM, HIGH)

NO_CHANGED_FILES = "NO_CHANGED_FILES"
NOT_CHECKED_NO_MUTATION = "NOT_CHECKED_NO_MUTATION"
IMPACT_RISKS = (
    NO_CHANGED_FILES,
    NOT_CHECKED_NO_MUTATION,
    LOW,
    MEDIUM,
    HIGH,
)

CLEAN_CORE = "CLEAN_CORE"
NEEDS_USER_GATE = "NEEDS_USER_GATE"
BLOCKED = "BLOCKED"
NOT_CHECKED = "NOT_CHECKED"
INVALID_EVIDENCE = "INVALID_EVIDENCE"
STATUSES = (
    CLEAN_CORE,
    NEEDS_USER_GATE,
    BLOCKED,
    NOT_CHECKED,
    INVALID_EVIDENCE,
)

STATE_DIR = ".aeg"
CONFIG_FILE = "config.json"
LEDGER_FILE = "ledger.jsonl"
RUNS_DIR = "runs"
