"""Shared Day-1 contract vocabulary."""

AEG_VERSION = "0.1.0"
SAFE_DEFAULT = "hold_current_state"

LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
RISK_LEVELS = (LOW, MEDIUM, HIGH)
RISK_ORDER = {
    LOW: 0,
    MEDIUM: 1,
    HIGH: 2,
}

NO_CHANGED_FILES = "NO_CHANGED_FILES"
NOT_CHECKED = "NOT_CHECKED"
NOT_CHECKED_NO_MUTATION = "NOT_CHECKED_NO_MUTATION"
NOT_CHECKED_IMPACT_RISKS = (
    NOT_CHECKED,
    NOT_CHECKED_NO_MUTATION,
)
IMPACT_RISKS = (
    NO_CHANGED_FILES,
    NOT_CHECKED,
    NOT_CHECKED_NO_MUTATION,
    LOW,
    MEDIUM,
    HIGH,
)

GIT_WORKING_TREE = "git_working_tree"
GIT_STAGED = "git_staged"
GIT_TRACKED_DIFF = "git_tracked_diff"
NO_CHANGED_FILES_SOURCE = "no_changed_files"
NOT_CHECKED_SOURCE = "not_checked"
CHANGED_FILES_SOURCES = (
    GIT_WORKING_TREE,
    GIT_STAGED,
    GIT_TRACKED_DIFF,
    NO_CHANGED_FILES_SOURCE,
    NOT_CHECKED_SOURCE,
)

CLEAN_CORE = "CLEAN_CORE"
NEEDS_USER_GATE = "NEEDS_USER_GATE"
BLOCKED = "BLOCKED"
INVALID_EVIDENCE = "INVALID_EVIDENCE"
STATUSES = (
    CLEAN_CORE,
    NEEDS_USER_GATE,
    BLOCKED,
    NOT_CHECKED,
    INVALID_EVIDENCE,
)

STATE_DIR = ".aeg"
CONFIG_FILE = "config.json"
LEDGER_FILE = "ledger.jsonl"
RUNS_DIR = "runs"

CONTRACT_FIRST_NOOP = "contract_first_noop"
COMPLETION_CONTRACT_V0 = "completion_contract_v0"

RUN_MANIFEST_V1 = "run_manifest_v1"
EVIDENCE_BINDING_V1 = "evidence_binding_v1"
BOUND = "BOUND"
BINDING_STATUSES = (
    BOUND,
    INVALID_EVIDENCE,
    NOT_CHECKED,
)

GIT_STATUS_PORCELAIN_V1 = "git_status_porcelain_v1"
SNAPSHOT_COLLECTOR_GIT_STATUS_V1 = "aeg_git_status_snapshot_v1"
SNAPSHOT_TRUST_BOUNDARY_CLI_WRAPPER_V1 = "aeg_cli_pre_post_executor_wrapper_v1"

MUTATION_DELTA_SOURCE_COMPUTED = "computed_from_independent_snapshots"
MUTATION_DELTA_SOURCE_UNTRUSTED = "not_checked_untrusted_snapshot"
REPORTED_ONLY = "reported_only"

MUTATION_BOUNDARY_CLEAN = "MUTATION_BOUNDARY_CLEAN"
MUTATION_BOUNDARY_DIRTY_PREEXISTING = "MUTATION_BOUNDARY_DIRTY_PREEXISTING"
MUTATION_BOUNDARY_DELTA_DETECTED = "MUTATION_BOUNDARY_DELTA_DETECTED"
MUTATION_BOUNDARY_UNTRUSTED_SNAPSHOT = "MUTATION_BOUNDARY_UNTRUSTED_SNAPSHOT"
MUTATION_BOUNDARY_NOT_CHECKED = "MUTATION_BOUNDARY_NOT_CHECKED"
MUTATION_BOUNDARY_STATUSES = (
    MUTATION_BOUNDARY_CLEAN,
    MUTATION_BOUNDARY_DIRTY_PREEXISTING,
    MUTATION_BOUNDARY_DELTA_DETECTED,
    MUTATION_BOUNDARY_UNTRUSTED_SNAPSHOT,
    MUTATION_BOUNDARY_NOT_CHECKED,
)
